[project]
name = "modmanager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pyinstaller>=6.18.0",
]

[project.scripts]
hello = "pyinstaller --onefile --icon=parakeet.ico --noconsole --name=Parakeet main.py"

[dependency-groups]
dev = []
